// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPHO2m4FtpNI4j7WGE9L7lee8FhT2YwXY',
    appId: '1:559288626136:web:c8729e885eca731e42e0ad',
    messagingSenderId: '559288626136',
    projectId: 'ankit-first-flutter-project',
    authDomain: 'ankit-first-flutter-project.firebaseapp.com',
    storageBucket: 'ankit-first-flutter-project.appspot.com',
    measurementId: 'G-JGXVFN9X7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OLJ4WPmAiIWggdssi16fGARceAEIXHc',
    appId: '1:559288626136:android:d462709227e6d2dc42e0ad',
    messagingSenderId: '559288626136',
    projectId: 'ankit-first-flutter-project',
    storageBucket: 'ankit-first-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC78wPIqPPBXzNh65wPMrZqLoHCfSbk_OM',
    appId: '1:559288626136:ios:56ef1d15d022eeaa42e0ad',
    messagingSenderId: '559288626136',
    projectId: 'ankit-first-flutter-project',
    storageBucket: 'ankit-first-flutter-project.appspot.com',
    iosClientId: '559288626136-crf11ikpkq4c8nqh95fv46vr1ikvkrvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );
}
